version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: movie-streaming-app:latest
    container_name: movie_streaming_app
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
